---
- name: Restart tomcat
  hosts: app
  become: true

  tasks:
    - name: Copy systemd service
      template:
        src: templates/tomcat.service.j2
        dest: /etc/systemd/system/tomcat.service

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable and restart Tomcat
      systemd:
        name: tomcat
        enabled: yes
        state: restarted