---
- name: Deploy Web Application on Amazon Linux 2023
  hosts: webservers
  become: yes

  vars:
    app_root: /usr/share/nginx/html
    server_name: _
    nginx_conf: /etc/nginx/conf.d/mywebsite.conf

  tasks:

    - name: Install Nginx
      dnf:
        name: nginx
        state: present

    - name: Start and Enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy website files
      copy:
        src: files/
        dest: "{{ app_root }}/"
        owner: nginx
        group: nginx
        mode: "0644"

    - name: Deploy Nginx configuration
      template:
        src: templates/nginx.conf.j2
        dest: "{{ nginx_conf }}"
        owner: root
        group: root
        mode: "0644"

    - name: Validate Nginx Configuration
      command: nginx -t
      register: nginx_test
      changed_when: false

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted